// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/billingadmin": {
    params: {};
  };
  "/sanpham": {
    params: {};
  };
  "/kho": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/pageshop/:id": {
    params: {
      "id": string;
    };
  };
  "/shop": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/security": {
    params: {};
  };
  "/MalikethPolicy": {
    params: {};
  };
  "/ReturnRefundPolicy": {
    params: {};
  };
  "/TermsOfService": {
    params: {};
  };
  "/dashboardUser": {
    params: {};
  };
  "/dashboardUser/billing": {
    params: {};
  };
  "/shearch/:keyword": {
    params: {
      "keyword": string;
    };
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/billingadmin" | "/sanpham" | "/kho" | "/product/:id" | "/pageshop/:id" | "/shop" | "/cart" | "/checkout" | "/security" | "/MalikethPolicy" | "/ReturnRefundPolicy" | "/TermsOfService" | "/dashboardUser" | "/dashboardUser/billing" | "/shearch/:keyword" | "/profile";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./src/components/page/LoginPage.jsx": {
    id: "src/components/page/LoginPage";
    page: "/login";
  };
  "./src/components/page/Dashborad.jsx": {
    id: "src/components/page/Dashborad";
    page: "/dashboard";
  };
  "./src/components/page/admin/bill/Billing.jsx": {
    id: "src/components/page/admin/bill/Billing";
    page: "/billingadmin";
  };
  "./src/components/page/admin/Sanpham.jsx": {
    id: "src/components/page/admin/Sanpham";
    page: "/sanpham";
  };
  "./src/components/page/admin/Kho.jsx": {
    id: "src/components/page/admin/Kho";
    page: "/kho";
  };
  "./src/components/page/ProductDetail.jsx": {
    id: "src/components/page/ProductDetail";
    page: "/product/:id";
  };
  "./src/components/page/PageShop.jsx": {
    id: "src/components/page/PageShop";
    page: "/pageshop/:id";
  };
  "./src/components/layout/CrateShop.jsx": {
    id: "src/components/layout/CrateShop";
    page: "/shop";
  };
  "./src/components/page/Cart.jsx": {
    id: "src/components/page/Cart";
    page: "/cart";
  };
  "./src/components/page/checkout.jsx": {
    id: "src/components/page/checkout";
    page: "/checkout";
  };
  "./src/components/ui/operating_policy/security.jsx": {
    id: "src/components/ui/operating_policy/security";
    page: "/security";
  };
  "./src/components/ui/operating_policy/MalikethPolicy.jsx": {
    id: "src/components/ui/operating_policy/MalikethPolicy";
    page: "/MalikethPolicy";
  };
  "./src/components/ui/operating_policy/ReturnRefundPolicy.jsx": {
    id: "src/components/ui/operating_policy/ReturnRefundPolicy";
    page: "/ReturnRefundPolicy";
  };
  "./src/components/ui/operating_policy/TermsOfService.jsx": {
    id: "src/components/ui/operating_policy/TermsOfService";
    page: "/TermsOfService";
  };
  "./src/components/page/dashborad_user/Dashborad.jsx": {
    id: "src/components/page/dashborad_user/Dashborad";
    page: "/dashboardUser" | "/dashboardUser/billing";
  };
  "./src/components/page/dashborad_user/Billing.jsx": {
    id: "src/components/page/dashborad_user/Billing";
    page: "/dashboardUser/billing";
  };
  "./src/components/ui/shearch/Sheacrch_Detail.jsx": {
    id: "src/components/ui/shearch/Sheacrch_Detail";
    page: "/shearch/:keyword";
  };
  "./src/components/page/profile/Profile.jsx": {
    id: "src/components/page/profile/Profile";
    page: "/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "src/components/page/LoginPage": typeof import("./app/./src/components/page/LoginPage.jsx");
  "src/components/page/Dashborad": typeof import("./app/./src/components/page/Dashborad.jsx");
  "src/components/page/admin/bill/Billing": typeof import("./app/./src/components/page/admin/bill/Billing.jsx");
  "src/components/page/admin/Sanpham": typeof import("./app/./src/components/page/admin/Sanpham.jsx");
  "src/components/page/admin/Kho": typeof import("./app/./src/components/page/admin/Kho.jsx");
  "src/components/page/ProductDetail": typeof import("./app/./src/components/page/ProductDetail.jsx");
  "src/components/page/PageShop": typeof import("./app/./src/components/page/PageShop.jsx");
  "src/components/layout/CrateShop": typeof import("./app/./src/components/layout/CrateShop.jsx");
  "src/components/page/Cart": typeof import("./app/./src/components/page/Cart.jsx");
  "src/components/page/checkout": typeof import("./app/./src/components/page/checkout.jsx");
  "src/components/ui/operating_policy/security": typeof import("./app/./src/components/ui/operating_policy/security.jsx");
  "src/components/ui/operating_policy/MalikethPolicy": typeof import("./app/./src/components/ui/operating_policy/MalikethPolicy.jsx");
  "src/components/ui/operating_policy/ReturnRefundPolicy": typeof import("./app/./src/components/ui/operating_policy/ReturnRefundPolicy.jsx");
  "src/components/ui/operating_policy/TermsOfService": typeof import("./app/./src/components/ui/operating_policy/TermsOfService.jsx");
  "src/components/page/dashborad_user/Dashborad": typeof import("./app/./src/components/page/dashborad_user/Dashborad.jsx");
  "src/components/page/dashborad_user/Billing": typeof import("./app/./src/components/page/dashborad_user/Billing.jsx");
  "src/components/ui/shearch/Sheacrch_Detail": typeof import("./app/./src/components/ui/shearch/Sheacrch_Detail.jsx");
  "src/components/page/profile/Profile": typeof import("./app/./src/components/page/profile/Profile.jsx");
};